[package]
name = "forrs-data"
version = "0.0.1"
authors = ["Follpvosten <wolfi@karpador.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }