CREATE TABLE "User" (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR (32) UNIQUE NOT NULL,
  pw_hash VARCHAR(64) NOT NULL,
  registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE Category (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR (64) UNIQUE NOT NULL
);
CREATE TABLE Topic (
  id BIGSERIAL PRIMARY KEY,
  category_id BIGINT REFERENCES Category(id) NULL,
  creator_id BIGINT REFERENCES "User"(id) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  edited_at TIMESTAMPTZ DEFAULT NULL,
  title VARCHAR(128) NOT NULL
);
CREATE SEQUENCE post_id_seq MINVALUE -2147483648 MAXVALUE 2147483647;
CREATE TABLE Post (
  topic_id BIGINT REFERENCES Topic(id),
  id INT DEFAULT NEXTVAL('post_id_seq'),
  author_id BIGINT REFERENCES "User"(id) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  edited_at TIMESTAMPTZ DEFAULT NULL,
  content TEXT NOT NULL,
  PRIMARY KEY (topic_id, id)
);