CREATE TABLE User (
  id SERIAL PRIMARY KEY,
  name VARCHAR (32) UNIQUE NOT NULL,
  pw_hash VARCHAR(64) NOT NULL,
  registered_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Category (
  id SERIAL PRIMARY KEY,
  name VARCHAR (64) UNIQUE NOT NULL
);
CREATE TABLE Topic (
  id SERIAL PRIMARY KEY,
  category_id BIGINT UNSIGNED REFERENCES Category(id),
  creator_id BIGINT UNSIGNED NOT NULL REFERENCES User(id),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  edited_at DATETIME DEFAULT NULL,
  title VARCHAR(128) NOT NULL
);
CREATE TABLE Post (
  topic_id BIGINT UNSIGNED REFERENCES Topic(id),
  id SERIAL,
  author_id BIGINT UNSIGNED NOT NULL REFERENCES User(id),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  edited_at DATETIME DEFAULT NULL,
  content TEXT NOT NULL,
  PRIMARY KEY (topic_id, id)
);