CREATE SEQUENCE user_id_seq MINVALUE -2147483648 MAXVALUE 2147483647;
CREATE TABLE "User" (
  id INT PRIMARY KEY DEFAULT NEXTVAL('user_id_seq'),
  name VARCHAR (32) UNIQUE NOT NULL,
  pw_hash VARCHAR(64) NOT NULL,
  registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE SEQUENCE category_id_seq MINVALUE -2147483648 MAXVALUE 2147483647;
CREATE TABLE Category (
  id INT PRIMARY KEY DEFAULT NEXTVAL('category_id_seq'),
  name VARCHAR (64) UNIQUE NOT NULL
);
CREATE SEQUENCE topic_id_seq MINVALUE -2147483648 MAXVALUE 2147483647;
CREATE TABLE Topic (
  id INT PRIMARY KEY DEFAULT NEXTVAL('topic_id_seq'),
  category_id INT REFERENCES Category(id) NULL,
  creator_id INT REFERENCES "User"(id) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  edited_at TIMESTAMPTZ DEFAULT NULL,
  title VARCHAR(128) NOT NULL
);
CREATE SEQUENCE post_id_seq MINVALUE -2147483648 MAXVALUE 2147483647;
CREATE TABLE Post (
  id INT DEFAULT NEXTVAL('post_id_seq'),
  topic_id INT REFERENCES Topic(id),
  author_id INT REFERENCES "User"(id) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  edited_at TIMESTAMPTZ DEFAULT NULL,
  content TEXT NOT NULL,
  PRIMARY KEY (topic_id, id)
);